<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermRepository extends EntityRepository
{
    /**
     * @param string $lang
     * @param Discipline $discipline
     *
     * @return Term
     *
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findRandomTerm($lang, Discipline $discipline = null)
    {
        //Retrieve the EntityManager first
        $em = $this->getEntityManager();

        //Get the number of rows from your table
        $rows = $em->createQuery('SELECT COUNT(t.id) FROM AppBundle:Term t WHERE t.lang = :lang')
            ->setParameter('lang', $lang)
            ->getSingleScalarResult()
        ;
        $offset = max(0, rand(0, $rows - 1));

        //Get the first term starting from a random point
        $query = $em->createQuery('SELECT t FROM AppBundle:Term t WHERE t.lang = :lang')
            ->setMaxResults(1)
            ->setFirstResult($offset)
            ->setParameter('lang', $lang)
        ;

        return $query->getSingleResult();
    }

}
